### ISSUE TITLE
Main functions not working

### ISSUE THREAD

**Issue by RamenNoodles** [AUSTIN2526/holocure-trainer#10]
I'm using steam, game ver. 0.6.1692303599

When I hit "detect" at the main menu I get a message saying "Scan Successful".

I activate all the main functions and start a game and non of the functions are working.

**Comment by AUSTIN2526** [comment]
The current latest version corresponding to the modifier is Holocure 0.6.1692236265. Therefore, dynamic modification will be ineffective.I have already incorporated the latest version's data for modification.

For the Save editor, the latest version requires making modifications after closing the game. Otherwise, the game will automatically overwrite the changes.

**Comment by AUSTIN2526** [comment]
All functionalities have been updated successfully. You can try again now.
