### ISSUE TITLE
Doesn't unlock (or removed all of them if already unlocked) Gen 3 & 4

### ISSUE THREAD

**Issue by azkicuteidol** [AUSTIN2526/holocure-trainer#19]

**Comment by AUSTIN2526** [comment]
This problem, as described in [#17 ](https://github.com/AUSTIN2526/holocure-trainer/issues/17#issuecomment-2510461640), occurs because the save editor's content currently only supports version 6.0. As a result, it doesn't unlock and removes Gen 3 & 4 characters if they were already unlocked.

This issue is actually easy to solve, but considering the substantial updates in version 7.0, I'll temporarily wait for someone to provide a complete save file before proceeding with the update. Alternatively, I might unlock all the items myself when I have some free time.

**Comment by AUSTIN2526** [comment]
The issue has been resolved! Please re-download the latest version of the file to access the full features. If you encounter any further issues, feel free to report them.
